blog/views/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from sqlalchemy.exc import IntegrityError

from blog.models.database import db
from blog.models import User
from blog.forms.user import RegistrationForm
from werkzeug.exceptions import NotFound
from blog.forms.user import RegistrationForm, LoginForm

auth_app = Blueprint("auth_app", __name__)
login_manager = LoginManager()
login_manager.login_view = "auth_app.login"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter_by(id=user_id).one_or_none()


@login_manager.unauthorized_handler
def unauthorized():
    return redirect(url_for("auth_app.login"))


__all__ = [
    "login_manager",
    "auth_app",
]


@auth_app.route("/login", methods=["GET", "POST"], endpoint="login")
def login():
    if current_user.is_authenticated:
        return redirect("index")

    form = LoginForm(request.form)

    if request.method == "POST" and form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).one_or_none()
        if user is None:
            return render_template("auth/login.html", form=form, error="username doesn't exist")
        if not user.validate_password(form.password.data):
            return render_template("auth/login.html", form=form, error="invalid username or password")
        login_user(user)
        return redirect(url_for("index"))
    return render_template("auth/login.html", form=form)


@auth_app.route("/logout", endpoint="logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("index"))


@auth_app.route("/login-as/", methods=["GET", "POST"], endpoint="login-as")
def login_as():
    if not (current_user.is_authenticated and current_user.is_staff):
    # non-admin users should not know about this feature
        raise NotFound

@auth_app.route("/secret")
@login_required
def secret_view():
    return "Super secret data"

@auth_app.route("/register/", methods=["GET", "POST"], endpoint="register")
def register():


    if current_user.is_authenticated:
        return redirect("index")
    error = None
    form = RegistrationForm(request.form)
    if request.method == "POST" and form.validate_on_submit():
        if User.query.filter_by(username=form.username.data).count():
            form.username.errors.append("username already exists!")
            return render_template("auth/register.html", form=form)

        if User.query.filter_by(email=form.email.data).count():
            form.email.errors.append("email already exists!")
            return render_template("auth/register.html", form=form)

        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            is_staff=False,
        )
        user.password = form.password.data
        db.session.add(user)
        try:
            db.session.commit()
        except IntegrityError:
            current_app.logger.exception("Could not create user!")
            error = "Could not create user!"
        else:
            current_app.logger.info("Created user %s", user)
            login_user(user)
            return redirect(url_for("index"))
    return render_template("auth/register.html", form=form, error=error)

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">

    <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

    <title>
        {% block title %}
        Base
        {% endblock %}
    </title>
</head>
<body>
<
<div class="container">
    {% block body %}
    Hello base!
    {% endblock %}
</div>
<nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('index') }}">Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% for (endpoint, label) in [('users_app.list', 'Users'), ('articles_app.list', 'Articles')] %}
                <a href="{{ url_for(endpoint) }}"
                   class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                    {{ label }}
                </a>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="navbar-nav ms-auto">
        {% if current_user.is_authenticated %}
        <a class="nav-link" href="{{ url_for('auth_app.logout') }}">Logout</a>
        {% else %}
            {% for (endpoint, label) in [
                            ('users_app.list', 'Users'),
                            ('articles_app.list', 'Articles'),
                            ('authors_app.list', 'Authors'), ] %}
                <a href="{{ url_for(endpoint) }}"
                class="nav-link {% if request.endpoint == endpoint -%}active{%- endif %}">
                {{ label }}
                </a>
            {% endfor %}
        {% endif %}
    </div>

</nav>
</body>
</html>

blog/templates/index.html
{% extends 'base.html' %}
{% block title %}
Index Page
{% endblock %}
{% block body %}
<h1>
    Hello
    {% if current_user.is_authenticated %}
    {{ current_user.username }}
    {% else %}
    anon
    {% endif %}
</h1>
{% endblock %}